apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: myjfrogapp
  title: Example JFrog for RHDH
  description: |
    This is the example JFrog component for RHDH
  annotations:
    #argocd/app-name: 'myjfrogapp'
    #backstage.io/kubernetes-id: 'myjfrogapp'
    #backstage.io/kubernetes-namespace: devhub-omolinab
    #github.com/project-slug: myorg/myjfrogapp
    #quay.io/repository-slug: openshift/okd
    #jfrog-artifactory/image-name: 'hello-world-maven-remote-cache/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar'
    jfrog-artifactory/image-name: 'hello-world-libs-release/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar'
spec:
  type: module
  system: myjfrogapp
  owner: team1
  lifecycle: experimental
