apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
  namespace: openshift-gitops
  labels:
    app: spring-petclinic
spec:
  destination:
    namespace: devhub-omolinab
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: petclinic
    repoURL: https://github.com/RedHatQuickCourses/devhub-qc-apps.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
